---
title: "Draft"
author: "Linda Tang"
date: "8/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
bike <- read_csv("210830_bikecrash.csv")
```

## Data used

crashes = number of cashes (count)
traffic_vol = mean traffic vol (numeric)
pct_rural = percentage of rural pop (numeric)

## Numerical implementation of Poisson regression

```{r}
m1 <- glm(crashes ~ traffic_vol + pct_rural, 
          data = bike, family = "poisson")
round(summary(m1)$coef[,1], 4)
```


```{r}
bike$intercept = 1
X <- bike %>%
  select(intercept, traffic_vol, pct_rural)
y <- bike$crashes

#median(bike$crashes)
beta_old <- c(5, 0.1, 0.1)
#beta_old <- matrix(beta_old, ncol = 1)
y <- matrix(y, ncol = 1)
X = data.matrix(X)
colnames(X) <- NULL
```

```{r}
# calculating the score
calc.score <- function(beta, X, y){
  d1 <- rep(0, length(beta))
  for(i in 1:length(y)){
    d1 <- d1 + (y[i] - exp(X[i,] %*% beta)) %*% X[i,]
  }
  return(colSums(d1))
}

calc.hess <- function(beta, X, y){
  d1 <- 0 # the result will be a number
  for(i in 1:length(y)){
    d1 <- d1 + (exp(X[i,] %*% beta)%*%(t(X[i,])%*%X[i,]))
  }
  return(-d1) # returns the negative num
}
```


```{r}
# repeat{
#   beta_new = beta_old - solve(calc.hess(beta_old, X, y)) %*% calc.score(beta_old, X, y)
#   # if (all(beta_new - beta_old < 0.00000000000000000000000001)){ #vector differences
#   #   break
#   # }
#   beta_old <- beta_new
# }
```

```{r}
#calc.score(beta_old, X, y)
matrix(calc.score(beta_old, X, y), nrow = 1)
```

```{r}
for(i in 1:1000000){
  beta_new = beta_old - solve(calc.hess(beta_old, X, y)) %*% calc.score(beta_old, X, y)
  beta_old <- beta_new[1,]
  if (i > 5000){
    break
  }
}
```

```{r}
 beta_old

beta_old <- c(5, 0.1, 0.1)

# grid search 

```


