---
title: "Newton-Raphson"
author: "Linda Tang"
date: "8/30/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
bike <- read_csv("210830_bikecrash.csv")
```

### Output using GLM

```{r}
m1 <- glm(crashes ~ traffic_vol + pct_rural, 
          data = bike, family = "poisson")
round(summary(m1)$coef[,1], 4)
```

## Numerical implementation of Poisson regression

```{r}
# Prepare data for computation
bike$intercept = 1
X <- bike %>% select(intercept, traffic_vol, pct_rural)
y <- bike$crashes

y <- matrix(y, ncol = 1)
X <- data.matrix(X)
colnames(X) <- NULL

# Initialize beta
beta <- c(1, 0.1, 0.1) # current dimension 3*1
```

```{r}
# calculating the score
calc.score <- function(beta, X, y){
  d1 <- rep(0, length(beta))
  for(i in 1:length(y)){
    d1 <- d1 + (y[i] - exp(X[i,] %*% beta)) %*% X[i,]
  }
  return(t(d1)) # returns 3*1 matrix
}

#calculating hessian matrix
calc.hess <- function(beta, X, y){
  d1 <- matrix(rep(0,9), ncol=3)
  for(i in 1:length(y)){
    d1 <- d1 + (exp(X[i,] %*% beta)[1,1]*(X[i,]%*%t(X[i,])))
  }
  return(-d1) # returns 3*3 matrix 
}
```

```{r}
iter = 1

while (iter <= 100){ # max 100 iter
  
  beta_new = beta- t(solve(calc.hess(beta, X, y)) %*% calc.score(beta, X, y))[1,]
  # 1*3 vector = 1*3 vector - t(  3*3 matrix %*% 3*1 matrix    )'s first row
  # 1*3 vector = 1*3 vector - 1*3 vector
  
  if (dist(rbind(beta, beta_new)) < 0.000000001){ 
    # using distance between vector to define convergence
    print("satisfied criteria of convergence")
    print("stopped at:")
    print(iter)
    break
  }
  beta <- beta_new
  iter = iter + 1
}
```

```{r}
beta # matchs
```

(Note: I found whether the convergence criteria is met depends on the initial value. It works well when I set beta to (1, 0.1, 0.1), but if I set it to something too far from the solution it's unable to converge, especially for beta2, and beta3. It runs into the issue of singular matrix). 